version: "3"
services:
  nginx_ssl:
    build: .
    ports:
      - "8443:443"
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - webnet

  backend:
    image: twoway-auth-box-jetty
    ports:
      - "18082:8080"
    networks:
      - webnet

networks:
  webnet: