version: "3"
services:

  nginx_ssl:
    build: .
    ports:
      - "8443:443"
    links:
      - upstream_server:upstream-server
    volumes:
      - ./certs:/etc/nginx/certs/
    networks:
      - webnet

  upstream_server:
    image: twoway-auth-box-jetty
    ports:
      - "18080:8080"
    networks:
      - webnet

networks:
  webnet: